### PR TITLE
[VG-29] Create storage room

### PR DESCRIPTION
**Pull request by JeremyNathanJusuf**

### CODE REVIEW

**Comment by JeremyNathanJusuf** [comment]
Current version has not implemented viewing content of galaxy phone, as well as the right image function and API

**Review by YoNG-Zaii — CHANGES_REQUESTED** [review]
@iujinwee Kindly update this branch with the relevant room links.

**Review by YoNG-Zaii — DISMISSED** [review]
LGTM. @JeremyNathanJusuf good to go.

**Review by KZY20112001 — APPROVED** [review]
lgtm

**Pull request merged**
