### PR TITLE
[VG-32] Update Room APIs

### PR DESCRIPTION
**Pull request by iujinwee**
Updated room API and Updated logic for fetchCharacter

### CODE REVIEW

**Review by YoNG-Zaii — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Review by JeremyNathanJusuf — APPROVED** [review]

**Review by YoNG-Zaii — CHANGES_REQUESTED** [review]
@JeremyNathanJusuf Please fix the pointer cursor when hovering over the background image.

**Review by YoNG-Zaii — CHANGES_REQUESTED** [review]
@JeremyNathanJusuf Pls check every room and make sure the import is like this:
import { CldImage } from "../components/ImageComp";
and not import CldImage from "../components/ImageComp";

**Review by JeremyNathanJusuf — APPROVED** [review]

**Review by YoNG-Zaii — APPROVED** [review]
Nice job!

**Pull request merged**
